name: 02 - Workflow Events

on:
  pull_request:
  workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the triggered event
              run: echo "I was triggered by a(n) ${{ github.event_name}} event."
